name: simple_website

# Permission for github pages deployment 
permissions: write-all

# WHEN TO RUN THE WORKFLOW
on: 
  push:
    branches:
      - main

# CI/CD
# select VM for running the workflow
jobs:
  deploy:
    runs-on: ubuntu-latest

# get repo in VM machine
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        
# Test the workflow(CI)
      - name: Check if files exist
        run: |
          if [ -f index.html ]; then
            echo "index.html found ✅"
          else
            echo "index.html not found ❌"
            exit 1
          fi
          if [ -f styles.css ]; then
            echo "styles.css found ✅"
          else
            echo "styles.css not found ❌"
            exit 1
          fi
          if [ -f script.js ]; then
            echo "script.js found ✅"
          else
            echo "script.js not found ❌"
            exit 1
          fi

# Create dist directory and copy files
      - name: Create dist directory and copy files
        run: |
          mkdir -p dist
          cp index.html dist/
          cp styles.css dist/
          cp script.js dist/
          echo "Files copied to dist ✅"

# Deploy to GitHub Pages(CD)
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist # from dist folder to push in gh-pages branch